/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_clearsilver_HDF */

#ifndef _Included_org_clearsilver_HDF
#define _Included_org_clearsilver_HDF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_clearsilver_HDF
 * Method:    _init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_clearsilver_HDF__1init
  (JNIEnv *, jclass);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _dealloc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_clearsilver_HDF__1dealloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _readFile
 * Signature: (ILjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_clearsilver_HDF__1readFile
  (JNIEnv *, jobject, jint, jstring, jboolean);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _writeFile
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_clearsilver_HDF__1writeFile
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _writeFileAtomic
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_clearsilver_HDF__1writeFileAtomic
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _readString
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_clearsilver_HDF__1readString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _writeString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_clearsilver_HDF__1writeString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _getIntValue
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_clearsilver_HDF__1getIntValue
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _getValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_clearsilver_HDF__1getValue
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _setValue
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_clearsilver_HDF__1setValue
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _removeTree
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_clearsilver_HDF__1removeTree
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _setSymLink
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_clearsilver_HDF__1setSymLink
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _getObj
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_clearsilver_HDF__1getObj
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _getChild
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_clearsilver_HDF__1getChild
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _objChild
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_clearsilver_HDF__1objChild
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _objNext
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_clearsilver_HDF__1objNext
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _objName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_clearsilver_HDF__1objName
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _objValue
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_clearsilver_HDF__1objValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _copy
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_clearsilver_HDF__1copy
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     org_clearsilver_HDF
 * Method:    _dump
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_clearsilver_HDF__1dump
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
